
import { useState, useEffect } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { motion } from "framer-motion";
import { apiRequest } from "@/lib/queryClient";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { BarChart, Users, Heart, Camera, TrendingUp, Clock, Lightbulb, Target, AlertTriangle, CheckCircle, Zap } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

interface BehaviorAnalytics {
  totalActions: number;
  actionBreakdown: Record<string, number>;
  userEngagement: {
    totalUsers: number;
    averageActionsPerUser: number;
    mostActiveUsers: Array<{ email: string; actionCount: number }>;
  };
  popularContent: {
    mostLikedPhotos: Array<{ photoId: string; likes: number }>;
  };
}

interface AiInsight {
  id: string;
  insightType: string;
  category: string;
  insightData: any;
  confidence: number;
  sampleSize: number;
  lastUpdated: string;
}

interface DynamicRecommendation {
  id: string;
  type: 'success' | 'warning' | 'info' | 'urgent';
  title: string;
  description: string;
  action?: string;
  priority: number;
  autoGenerated: boolean;
  timestamp: string;
}

export function BehaviorAnalytics() {
  const { toast } = useToast();
  const queryClient = useQueryClient();

  // Fetch behavior analytics
  const { data: analytics, isLoading: analyticsLoading } = useQuery<BehaviorAnalytics>({
    queryKey: ["/api/admin/behavior-analytics"],
    refetchInterval: 30000, // Refresh every 30 seconds
  });

  

  if (analyticsLoading) {
    return <div className="text-center py-8">Načítání analytics...</div>;
  }

  if (!analytics) {
    return <div className="text-center py-8">Nejsou dostupná žádná data</div>;
  }

  return (
    <div className="space-y-6">
      {/* Overview Stats */}
      <div className="grid grid-cols-2 gap-4">
        <div className="text-center p-4 bg-blue-50 rounded-lg">
          <div className="text-2xl font-bold text-blue-600">
            {analytics.totalActions}
          </div>
          <div className="text-sm text-blue-700">Celkem akcí</div>
        </div>
        <div className="text-center p-4 bg-green-50 rounded-lg">
          <div className="text-2xl font-bold text-green-600">
            {analytics.userEngagement.totalUsers}
          </div>
          <div className="text-sm text-green-700">Aktivních uživatelů</div>
        </div>
      </div>

      {/* Action Breakdown */}
      <div className="space-y-3">
        <h4 className="font-medium text-sm flex items-center gap-2">
          <BarChart className="h-4 w-4" />
          Typ aktivit
        </h4>
        {Object.entries(analytics.actionBreakdown).map(([actionType, count]) => {
          const percentage = (count / analytics.totalActions) * 100;
          return (
            <div key={actionType} className="space-y-1">
              <div className="flex justify-between text-xs">
                <span className="capitalize">
                  {actionType.replace('_', ' ')}
                </span>
                <span>{count} ({percentage.toFixed(1)}%)</span>
              </div>
              <Progress value={percentage} className="h-2" />
            </div>
          );
        })}
      </div>

      {/* Most Active Users */}
      <div className="space-y-3">
        <h4 className="font-medium text-sm flex items-center gap-2">
          <Users className="h-4 w-4" />
          Nejaktivnější uživatelé
        </h4>
        <div className="space-y-2">
          {analytics.userEngagement.mostActiveUsers.slice(0, 5).map((user, index) => (
            <div key={user.email} className="flex justify-between items-center p-2 bg-gray-50 rounded">
              <div className="flex items-center gap-2">
                <Badge variant="outline">#{index + 1}</Badge>
                <span className="text-sm truncate">{user.email}</span>
              </div>
              <span className="text-sm font-medium">{user.actionCount} akcí</span>
            </div>
          ))}
        </div>
      </div>

      
    </div>
  );
}

export function AiInsightsDisplay() {
  // Fetch AI insights
  const { data: insights, isLoading: insightsLoading } = useQuery<AiInsight[]>({
    queryKey: ["/api/admin/ai-insights"],
    refetchInterval: 60000, // Refresh every minute
  });

  if (insightsLoading) {
    return <div className="text-center py-8">Načítání AI poznatků...</div>;
  }

  if (!insights || insights.length === 0) {
    return (
      <div className="text-center py-8">
        <p className="text-muted-foreground mb-4">
          Zatím nejsou dostupné žádné AI poznatky
        </p>
        <p className="text-sm text-muted-foreground">
          Použijte tlačítko "Vygenerovat AI poznatky" pro analýzu dat
        </p>
      </div>
    );
  }

  return (
    <div className="space-y-4">
      {insights.map((insight) => (
        <motion.div
          key={insight.id}
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.3 }}
        >
          <Card className="border-l-4 border-l-blue-500">
            <CardHeader className="pb-3">
              <div className="flex justify-between items-start">
                <div>
                  <CardTitle className="text-sm font-medium">
                    {insight.category === 'technical_quality' ? 'Technická kvalita' : 
                     insight.category === 'emotional_content' ? 'Emoční obsah' : 
                     insight.category}
                  </CardTitle>
                  <div className="flex items-center gap-2 mt-1">
                    <Badge variant="outline" className="text-xs">
                      {insight.insightType.replace('_', ' ')}
                    </Badge>
                    <Badge 
                      variant={insight.confidence > 80 ? "default" : insight.confidence > 60 ? "secondary" : "destructive"}
                      className="text-xs"
                    >
                      {insight.confidence}% spolehlivost
                    </Badge>
                  </div>
                </div>
                <div className="text-xs text-muted-foreground">
                  {insight.sampleSize} vzorků
                </div>
              </div>
            </CardHeader>
            <CardContent className="space-y-3">
              <p className="text-sm text-muted-foreground">
                {insight.insightData.analysis}
              </p>
              
              {insight.insightData.preferences && (
                <div className="grid grid-cols-3 gap-2 text-xs">
                  <div className="text-center p-2 bg-blue-50 rounded">
                    <div className="font-medium">Ostrost</div>
                    <div>{(insight.insightData.preferences.sharpness * 100).toFixed(1)}%</div>
                  </div>
                  <div className="text-center p-2 bg-green-50 rounded">
                    <div className="font-medium">Kompozice</div>
                    <div>{(insight.insightData.preferences.composition * 100).toFixed(1)}%</div>
                  </div>
                  <div className="text-center p-2 bg-yellow-50 rounded">
                    <div className="font-medium">Osvětlení</div>
                    <div>{(insight.insightData.preferences.lighting * 100).toFixed(1)}%</div>
                  </div>
                </div>
              )}

              {insight.insightData.topEmotions && (
                <div className="space-y-2">
                  <div className="text-xs font-medium">Oblíbené emoce:</div>
                  <div className="flex flex-wrap gap-1">
                    {insight.insightData.topEmotions.slice(0, 5).map((emotion: any, index: number) => (
                      <Badge key={emotion.emotion} variant="outline" className="text-xs">
                        {emotion.emotion} ({emotion.count})
                      </Badge>
                    ))}
                  </div>
                </div>
              )}

              {insight.insightData.recommendations && (
                <div className="space-y-1">
                  <div className="text-xs font-medium">Doporučení:</div>
                  <ul className="text-xs text-muted-foreground space-y-1">
                    {insight.insightData.recommendations.map((rec: string, index: number) => (
                      <li key={index} className="flex items-start gap-1">
                        <span className="text-blue-500">•</span>
                        <span>{rec}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              <div className="text-xs text-muted-foreground pt-2 border-t">
                Aktualizováno: {new Date(insight.lastUpdated).toLocaleString('cs-CZ')}
              </div>
            </CardContent>
          </Card>
        </motion.div>
      ))}
    </div>
  );
}

// Komponenta pro dynamická AI doporučení
export function DynamicAiRecommendations() {
  const { toast } = useToast();
  const [recommendations, setRecommendations] = useState<DynamicRecommendation[]>([]);

  // Fetch behavior analytics for generating recommendations
  const { data: analytics } = useQuery<BehaviorAnalytics>({
    queryKey: ["/api/admin/behavior-analytics"],
    refetchInterval: 10000, // Refresh every 10 seconds
  });

  // Generate dynamic recommendations based on analytics
  useEffect(() => {
    if (!analytics) return;

    const newRecommendations: DynamicRecommendation[] = [];
    const now = new Date().toISOString();

    // Analýza aktivity uživatelů
    if (analytics.userEngagement.totalUsers < 5) {
      newRecommendations.push({
        id: 'low-engagement',
        type: 'warning',
        title: 'Nízká uživatelská aktivita',
        description: `Pouze ${analytics.userEngagement.totalUsers} aktivních uživatelů. Zvažte propagaci aplikace nebo aktivaci více výzev.`,
        action: 'Aktivovat více výzev s nižšími body',
        priority: 8,
        autoGenerated: true,
        timestamp: now
      });
    }

    // Analýza typu aktivit
    const uploadActions = analytics.actionBreakdown.photo_quest_upload || 0;
    const likeActions = analytics.actionBreakdown.photo_like || 0;
    
    if (likeActions < uploadActions * 0.5) {
      newRecommendations.push({
        id: 'low-engagement-ratio',
        type: 'info',
        title: 'Nízká interakce s fotkami',
        description: `Poměr lajků k uploadům je ${(likeActions / Math.max(uploadActions, 1)).toFixed(1)}:1. Uživatelé málo lajkují fotky.`,
        action: 'Přidejte gamifikaci pro lajkování',
        priority: 6,
        autoGenerated: true,
        timestamp: now
      });
    }

    // Analýza nejvíce aktivních uživatelů
    if (analytics.userEngagement.mostActiveUsers.length > 0) {
      const topUser = analytics.userEngagement.mostActiveUsers[0];
      if (topUser.actionCount > 20) {
        newRecommendations.push({
          id: 'power-user-detected',
          type: 'success',
          title: 'Velmi aktivní uživatel detekován!',
          description: `${topUser.email} má ${topUser.actionCount} akcí. Zvažte speciální odměnu.`,
          action: 'Pošlete osobní poděkování',
          priority: 7,
          autoGenerated: true,
          timestamp: now
        });
      }
    }

    // Analýza celkové aktivity
    if (analytics.totalActions > 100) {
      newRecommendations.push({
        id: 'high-activity',
        type: 'success',
        title: 'Vysoká aktivita platformy!',
        description: `Celkem ${analytics.totalActions} akcí. Aplikace je velmi úspěšná!`,
        action: 'Připravte více náročnějších výzev',
        priority: 9,
        autoGenerated: true,
        timestamp: now
      });
    }

    // Časové doporučení
    const hour = new Date().getHours();
    if (hour >= 18 && hour <= 22) {
      newRecommendations.push({
        id: 'peak-time',
        type: 'info',
        title: 'Špičková doba aktivity',
        description: 'Je večer - nejlepší čas pro publikování nových výzev nebo interakci s uživateli.',
        action: 'Publikujte nový obsah nyní',
        priority: 5,
        autoGenerated: true,
        timestamp: now
      });
    }

    // Seřaď podle priority
    newRecommendations.sort((a, b) => b.priority - a.priority);

    setRecommendations(newRecommendations.slice(0, 5)); // Zobraz max 5 doporučení
  }, [analytics]);

  const getRecommendationIcon = (type: DynamicRecommendation['type']) => {
    switch (type) {
      case 'success': return <CheckCircle className="h-4 w-4 text-green-600" />;
      case 'warning': return <AlertTriangle className="h-4 w-4 text-yellow-600" />;
      case 'urgent': return <Zap className="h-4 w-4 text-red-600" />;
      default: return <Lightbulb className="h-4 w-4 text-blue-600" />;
    }
  };

  const getRecommendationBorder = (type: DynamicRecommendation['type']) => {
    switch (type) {
      case 'success': return 'border-l-green-500';
      case 'warning': return 'border-l-yellow-500';
      case 'urgent': return 'border-l-red-500';
      default: return 'border-l-blue-500';
    }
  };

  if (!recommendations.length) {
    return (
      <div className="text-center py-8">
        <Lightbulb className="h-12 w-12 mx-auto text-gray-400 mb-4" />
        <p className="text-gray-500">Sbírání dat pro AI doporučení...</p>
        <p className="text-sm text-gray-400 mt-2">
          Doporučení se objeví automaticky na základě aktivity uživatelů
        </p>
      </div>
    );
  }

  return (
    <div className="space-y-3">
      <div className="flex items-center gap-2 mb-4">
        <Zap className="h-5 w-5 text-blue-600" />
        <h3 className="font-medium text-sm">Dynamická AI doporučení</h3>
        <Badge variant="outline" className="text-xs">
          Live • {recommendations.length} aktivních
        </Badge>
      </div>

      {recommendations.map((rec, index) => (
        <motion.div
          key={rec.id}
          initial={{ opacity: 0, x: -20 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ duration: 0.3, delay: index * 0.1 }}
        >
          <Card className={`border-l-4 ${getRecommendationBorder(rec.type)} hover:shadow-md transition-shadow`}>
            <CardContent className="p-4">
              <div className="flex items-start gap-3">
                <div className="mt-0.5">
                  {getRecommendationIcon(rec.type)}
                </div>
                <div className="flex-1 space-y-2">
                  <div className="flex items-center justify-between">
                    <h4 className="font-medium text-sm text-gray-900">
                      {rec.title}
                    </h4>
                    <div className="flex items-center gap-1">
                      <Badge 
                        variant={rec.priority > 7 ? "default" : "outline"} 
                        className="text-xs"
                      >
                        P{rec.priority}
                      </Badge>
                      {rec.autoGenerated && (
                        <Badge variant="secondary" className="text-xs">
                          Auto
                        </Badge>
                      )}
                    </div>
                  </div>
                  <p className="text-sm text-gray-600 leading-relaxed">
                    {rec.description}
                  </p>
                  {rec.action && (
                    <div className="pt-2">
                      <Button 
                        size="sm" 
                        variant="outline"
                        className="text-xs"
                        onClick={() => toast({ 
                          title: "Doporučení zaznamenáno", 
                          description: rec.action 
                        })}
                      >
                        <Target className="h-3 w-3 mr-1" />
                        {rec.action}
                      </Button>
                    </div>
                  )}
                  <div className="text-xs text-gray-400">
                    {new Date(rec.timestamp).toLocaleString('cs-CZ')}
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        </motion.div>
      ))}

      <div className="text-xs text-gray-500 text-center pt-2">
        Doporučení se aktualizují automaticky každých 10 sekund
      </div>
    </div>
  );
}

export default BehaviorAnalytics;
